run:
  go: '1.23'
  timeout: 5m

linters-settings:
  dupl:
    threshold: 100
  funlen:
    lines: 200
    statements: 200
linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - funlen
    - gocritic
    - gofmt
      # - goheader # TODO: enable goheader
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - funlen
        - gosec
        - gocritic
    - path: dialect/sql/schema
      linters:
        - dupl
        - gosec
    - text: "Expect WriteFile permissions to be 0600 or less"
      linters:
        - gosec
    - path: privacy/privacy.go
      linters:
        - stylecheck
    - path: \.go
      linters:
        - staticcheck
      text: SA1019
