// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"github.com/walkersumida/aws-sso-google/sts"
	"sync"
)

// Ensure, that STSerMock does implement sts.STSer.
// If this is not the case, regenerate this file with moq.
var _ sts.STSer = &STSerMock{}

// STSerMock is a mock implementation of sts.STSer.
//
//	func TestSomethingThatUsesSTSer(t *testing.T) {
//
//		// make and configure a mocked sts.STSer
//		mockedSTSer := &STSerMock{
//			AssumeRoleWithSAMLFunc: func() (*sts.Response, error) {
//				panic("mock out the AssumeRoleWithSAML method")
//			},
//			SetAwsPrincipalArnFunc: func(s string)  {
//				panic("mock out the SetAwsPrincipalArn method")
//			},
//			SetSAMLAssertionFunc: func(s string)  {
//				panic("mock out the SetSAMLAssertion method")
//			},
//		}
//
//		// use mockedSTSer in code that requires sts.STSer
//		// and then make assertions.
//
//	}
type STSerMock struct {
	// AssumeRoleWithSAMLFunc mocks the AssumeRoleWithSAML method.
	AssumeRoleWithSAMLFunc func() (*sts.Response, error)

	// SetAwsPrincipalArnFunc mocks the SetAwsPrincipalArn method.
	SetAwsPrincipalArnFunc func(s string)

	// SetSAMLAssertionFunc mocks the SetSAMLAssertion method.
	SetSAMLAssertionFunc func(s string)

	// calls tracks calls to the methods.
	calls struct {
		// AssumeRoleWithSAML holds details about calls to the AssumeRoleWithSAML method.
		AssumeRoleWithSAML []struct {
		}
		// SetAwsPrincipalArn holds details about calls to the SetAwsPrincipalArn method.
		SetAwsPrincipalArn []struct {
			// S is the s argument value.
			S string
		}
		// SetSAMLAssertion holds details about calls to the SetSAMLAssertion method.
		SetSAMLAssertion []struct {
			// S is the s argument value.
			S string
		}
	}
	lockAssumeRoleWithSAML sync.RWMutex
	lockSetAwsPrincipalArn sync.RWMutex
	lockSetSAMLAssertion   sync.RWMutex
}

// AssumeRoleWithSAML calls AssumeRoleWithSAMLFunc.
func (mock *STSerMock) AssumeRoleWithSAML() (*sts.Response, error) {
	if mock.AssumeRoleWithSAMLFunc == nil {
		panic("STSerMock.AssumeRoleWithSAMLFunc: method is nil but STSer.AssumeRoleWithSAML was just called")
	}
	callInfo := struct {
	}{}
	mock.lockAssumeRoleWithSAML.Lock()
	mock.calls.AssumeRoleWithSAML = append(mock.calls.AssumeRoleWithSAML, callInfo)
	mock.lockAssumeRoleWithSAML.Unlock()
	return mock.AssumeRoleWithSAMLFunc()
}

// AssumeRoleWithSAMLCalls gets all the calls that were made to AssumeRoleWithSAML.
// Check the length with:
//
//	len(mockedSTSer.AssumeRoleWithSAMLCalls())
func (mock *STSerMock) AssumeRoleWithSAMLCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockAssumeRoleWithSAML.RLock()
	calls = mock.calls.AssumeRoleWithSAML
	mock.lockAssumeRoleWithSAML.RUnlock()
	return calls
}

// SetAwsPrincipalArn calls SetAwsPrincipalArnFunc.
func (mock *STSerMock) SetAwsPrincipalArn(s string) {
	if mock.SetAwsPrincipalArnFunc == nil {
		panic("STSerMock.SetAwsPrincipalArnFunc: method is nil but STSer.SetAwsPrincipalArn was just called")
	}
	callInfo := struct {
		S string
	}{
		S: s,
	}
	mock.lockSetAwsPrincipalArn.Lock()
	mock.calls.SetAwsPrincipalArn = append(mock.calls.SetAwsPrincipalArn, callInfo)
	mock.lockSetAwsPrincipalArn.Unlock()
	mock.SetAwsPrincipalArnFunc(s)
}

// SetAwsPrincipalArnCalls gets all the calls that were made to SetAwsPrincipalArn.
// Check the length with:
//
//	len(mockedSTSer.SetAwsPrincipalArnCalls())
func (mock *STSerMock) SetAwsPrincipalArnCalls() []struct {
	S string
} {
	var calls []struct {
		S string
	}
	mock.lockSetAwsPrincipalArn.RLock()
	calls = mock.calls.SetAwsPrincipalArn
	mock.lockSetAwsPrincipalArn.RUnlock()
	return calls
}

// SetSAMLAssertion calls SetSAMLAssertionFunc.
func (mock *STSerMock) SetSAMLAssertion(s string) {
	if mock.SetSAMLAssertionFunc == nil {
		panic("STSerMock.SetSAMLAssertionFunc: method is nil but STSer.SetSAMLAssertion was just called")
	}
	callInfo := struct {
		S string
	}{
		S: s,
	}
	mock.lockSetSAMLAssertion.Lock()
	mock.calls.SetSAMLAssertion = append(mock.calls.SetSAMLAssertion, callInfo)
	mock.lockSetSAMLAssertion.Unlock()
	mock.SetSAMLAssertionFunc(s)
}

// SetSAMLAssertionCalls gets all the calls that were made to SetSAMLAssertion.
// Check the length with:
//
//	len(mockedSTSer.SetSAMLAssertionCalls())
func (mock *STSerMock) SetSAMLAssertionCalls() []struct {
	S string
} {
	var calls []struct {
		S string
	}
	mock.lockSetSAMLAssertion.RLock()
	calls = mock.calls.SetSAMLAssertion
	mock.lockSetSAMLAssertion.RUnlock()
	return calls
}
